# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 316cc5e12cd6312f8ea88a3a61a38dc1623ce0c6dde3d6680c336af6806fe64841fb38b8bf05f2d9edeef120af518903cc9b7a0ddb76d18ae2277e6fdb242fe4

test:
  secret_key_base: 131339bde560abc1c994b30e8b54f96e6ede7bd11cd8bc5b004b0e5d9d596dca552640ac2df6aefe11dbfd9ee6dadba28b29fe5ed47a9e5c96a0f85aa3ed9338

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
